

# This file was *autogenerated* from the file run.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10)
from p_rank_allsteps.sage import p_rank_allsteps

# Now call the function (with example arguments):  
p = _sage_const_3                          # Example: prime  
lambda_pairs = [(_sage_const_1 ,_sage_const_2 ),(_sage_const_3 ,_sage_const_4 )]  # Example: your list of pairs  
lower_m1 = _sage_const_5   
upper_m1 = _sage_const_10   
explicit_testing_3 = False    # or True, as needed  
print_progress = True         # or False  
  
# Call the algorithm and store the result  
D = p_rank_allsteps(p, lambda_pairs, lower_m1, upper_m1, explicit_testing_3, print_progress)  
  
print(D)                      # Or do whatever you want with the result  

